server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh   #payment_route ；路由的id，没有固定规则，但要求唯一，建议配合服务名
          # uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**  #断言，路径匹配后进行路由
        - id: payment_routh2   #payment_route ；路由的id，没有固定规则，但要求唯一，建议配合服务名
          # uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**  #断言，路径匹配后进行路由
#            - After=2020-03-21T15:41:45.891+08:00[Asia/Shanghai]
#            - Cookie=username,wf

eureka:
  instance:
    instance-id: cloud-gateway-service
    # hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true
