server:
  port: 80

#spring:
#  application:
#    name:
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
ribbon:
  # 建立链接所需要的超时时间，单位毫秒
  # 这里注意大小写的问题 readTimeout: 5000 不行
  ReadTimeout: 5000
  # 链接超时的最大时间，单位毫秒
  ConnectTimeout: 5000

logging:
  level:
    # feign以什么日志级别监控那个接口
    com.wf.springcloud.service.PaymentFeignService: debug